#!/usr/bin/env php
<?php
    require_once("/Users/jonas/Opensource/depage-cms/www/framework/depage/depage.php");
    
    // minify javascript
    $jsmin = \depage\jsmin\jsmin::factory(array(
        'extension' => "closureApi",
    ));
    $src = $jsmin->minifyFiles("global.min.js", array(
	"www/lib/global/js/jquery-1.8.3.min.js",
        "www/lib/global/htmlform/js/jquery.tools.min.js",
        "www/lib/global/htmlform/js/effect.js",
        "www/lib/global/comments/js/comments.js",
	"www/lib/global/depage-jquery-plugins/depage-slideshow.js",
	"www/lib/global/depage-jquery-plugins/depage-compare-images.js",
	"www/lib/global/depage-jquery-plugins/depage-email-antispam.js",
	"www/lib/global/depage-jquery-plugins/depage-social.js",
        "www/lib/global/js/jquery.history.js",
        "www/lib/global/js/ajaxify-html5.js",
	"www/lib/global/js/global.js",
    ));
    file_put_contents("www/lib/global/js/global.min.js", $src);

    // minify css
    $cssmin = \depage\cssmin\cssmin::factory(array(
    ));
    $src = $cssmin->minifyFiles("global.min.css", array(
        "www/lib/global/htmlform/css/depage-forms.css",
	"www/lib/global/css/global.css",
    ));
    file_put_contents("www/lib/global/css/global.min.css", $src);
        
// vim:set ft=php sw=4 sts=4 fdm=marker :
