#!/usr/bin/env php
<?php
    require_once("/Users/jonas/Opensource/depage-cms/www/framework/depage/depage.php");
    
    // minify javascript
    $jsmin = \depage\jsmin\jsmin::factory(array(
        'extension' => "closureApi",
    ));
    $src = $jsmin->minifyFiles("global.min.js", array(
        "www/lib/global/js/jquery-1.8.3.min.js",
        "www/lib/global/js/jquery.iframe-auto-height.plugin.js",
        "www/lib/global/js/global.js",
        "www/lib/global/js/search.js",
        "www/lib/global/js/dynsections.js",
    ));
    file_put_contents("www/lib/global/js/global.min.js", $src);

// vim:set ft=php sw=4 sts=4 fdm=marker :
