#!/bin/bash

./minimize --dp-path "$(pwd)"

rsync \
    -k -r -v -c \
    --exclude '.DS_Store' \
    --exclude '.git' \
    www/lib/global/ www-data@cms.depagecms.net:/var/www/net.depagecms.cms/projects/depage/lib/global/

rsync \
    -k -r -v -c \
    --exclude '.DS_Store' \
    --exclude '.git' \
    www/lib/global/ www-data@cms.depagecms.net:/var/www/net.depagecms.cms/projects/depagecms/lib/global/
